// <auto-generated />
namespace DemoFresher2021.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FoodTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FoodTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202205130350436_FoodTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
